### PR TITLE
Edited the Readme File

### LINKED ISSUE #100: Remove the Extra "Readme" Title in the Readme File
I was just scrolling through the repo admiring the header I made and saw there are 2 "Readme" title. I thought it's looking odd. So just edited it from my phone.
IMG_20221012_074801

### PR DESCRIPTION
**Pull request by chiragkhatri19**
### Describe your changes
Removed the Extra "Readme" Title and added some emojis to make it look good

#### Link to issue this resolves
# 100 

Fixes {REPLACE THIS WITH A LINK TO YOUR ISSUE}

#### Screenshot of changes(if relevant)
Screenshot 2022-10-12 104419

* [x] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_

##### This **description** should include :
* [x] A short summary of your changes
* [x] A link to the issue that relates to these changes
* [x] A screenshot of the changes if possible!

### CODE REVIEW

**Comment by brittanyjoiner15** [comment]
@chiragkhatri19 i'm sorry this is not tied to an issue so we can't accept it, and it's a very minimal change and probably doesn't warrant a PR :) In the future please create issues and then I will review them and assign to you if they're worthwhile. Thanks!

**Comment by chiragkhatri19** [comment]
> @chiragkhatri19 i'm sorry this is not tied to an issue so we can't accept it, and it's a very minimal change and probably doesn't warrant a PR :) In the future please create issues and then I will review them and assign to you if they're worthwhile. Thanks!

I already made a **issue #100** regarding this and you assigned it to me. So, I edited it and made a PR.

**Comment by brittanyjoiner15** [comment]
@chiragkhatri19 ah i did not see the linked issue, and thought this was just additions of emojis. I will reopen but can we remove the emojis and just stick with the original issue, which is removing the duplicate `readme`?

**Comment by chiragkhatri19** [comment]
> @chiragkhatri19 ah i did not see the linked issue, and thought this was just additions of emojis. I will reopen but can we remove the emojis and just stick with the original issue, which is removing the duplicate `readme`?

Okay I'll do it

**Comment by brittanyjoiner15** [comment]
Closing this since I merged this one: https://github.com/brittanyjoiner15/eui-event-template/pull/106

Thanks @chiragkhatri19 !

**Pull request closed without merging**
