### PR TITLE
Added Sort By Date and Title to Talks -> issue #12

### PR DESCRIPTION
**Pull request by ranaDherya**
#### Describe your changes
Added Sort by Date and Title functionality to Talks Table section.

#### Link to issue this resolves
https://github.com/brittanyjoiner15/eui-event-template/issues/12

# 12 
#### Screenshot of changes(if relevant)

* [ ] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_
* [ ] This **description** should include ...
  * [ ] A short summary of your changes
  * [ ] A link to the issue that relates to these changes
  * [ ] A screenshot of the changes if possible!
* [ ] Add `brittanyjoiner15` as a reviewer
* [ ] Add yourself as assignee

### CODE REVIEW

**Review by brittanyjoiner15 — CHANGES_REQUESTED** [review]
So i was expecting this to be used with the `sort` prop on EuiBasicTable ([see docs here](https://elastic.github.io/eui/#/tabular-content/tables#a-basic-table)), but I can appreciate all the work you've put into this! Do you think you'd be able to implement the `sort` prop? (Check out the DemoJS and Props section in that link and let me know what you think.)

**Comment by ranaDherya** [comment]
@brittanyjoiner15 
are the function i created for sortByDate and sortByTitle correct and I just have to implement sort prop to call those functions? Or do I have change these functions too?

**Comment by brittanyjoiner15** [comment]
@ranadherya I believe those functions would be unnecessary within Eui. Check out the implementation on those docs - let me know if it doesn't make sense and I can look a little more and record a loom explaining it

**Comment by brittanyjoiner15** [comment]
@ranaDherya just wanted to check in on this and see how it's going or if you need any help!

**Comment by ranaDherya** [comment]
Hey @brittanyjoiner15, sorry I got busy because of festivals, will start working on this from tomorrow

**Comment by brittanyjoiner15** [comment]
@ranaDherya sounds great! please share an update tomorrow with your progress, thanks!

**Comment by ranaDherya** [comment]
hey @brittanyjoiner15 ,
`import { createDataStore } from '../data_store';` this data_store file is not available.
`const { pageOfItems, totalItemCount } = store.findUsers(
    pageIndex,
    pageSize,
    sortField,
    sortDirection
  );`

so this function is not working

**Comment by brittanyjoiner15** [comment]
@ranaDherya can you try fixing the merge conflicts and pulling from main and seeing if those functions still don't work?

**Comment by brittanyjoiner15** [comment]
@ranaDherya let me know if you need help with any of the merge conflicts!

**Comment by brittanyjoiner15** [comment]
@ranaDherya just wanted to check on in this. i haven't heard anything in the last two weeks, so i will close this and re-assign the issue but feel free to re-open if you're still working on it.

**Pull request closed without merging**
