### PR TITLE
Add accessibility checklist

### LINKED ISSUE #79: Create an accessibility checklist
Add a section to the bottom of the  https://github.com/brittanyjoiner15/eui-event-template/blob/main/docs/research-notes.md file with a checklist of things that we should consider for improving accessibility on the site.

Ideally, you will make a checklist and then :white_check_mark: off any items the site is already doing well with, and then mention any areas that we specifically need to improve so that we can easily convert those into issues for people to tackle.

### PR DESCRIPTION
**Pull request by bpvcode**
### Describe your changes
* [x] Add a table with tasks to improve website accessibility under `./docs/research-notes.md`;
*  [X] Mark as `DONE` the ones that are already done;
*  [X] Mark as `TODO` the ones that need to be done;
*  [X] Mark as `TO CHECK` the ones that need someone to look into and improve that or mark as done;

**NOTES:**

* Only applied tasks/rules that are applicable to the website as it is right now, when we improve the website, new rules/tasks should be added. Example - If we have videos:
* `<video>` elements contain a `<track>` element with `[kind="captions"]` , level of priority `AA`, [documentation](https://dequeuniversity.com/rules/axe/4.4/video-caption?utm_source=lighthouse&utm_medium=lr)

#### Link to issue this resolves
The issue to resolve: #79 

Reviewer: brittanyjoiner15 
Assignee:  bpvcode

#### Screenshot
accessibility!UNITO-UNDERSCORE!checklist

### CODE REVIEW

**Comment by bpvcode** [comment]
Hello @brittanyjoiner15 ,

This is the first implementation of the accessibility checklist.

I tried to input only applicable tasks for the website as it is right now. Of course, we should improve this list over time when more features are added.

I already identified some tasks that need to be done, and others that we should check if it's done or not.
Once that are 2 more people wanting to contribute to this issue, I thought that could be a great idea open 2 more issues, 1 to do the tasks that are in `TODO` status, and another to check and resolve if necessary the tasks that are in `TO CHECK` status. And give them the possibility to improve this list as well if they find some more relevant tasks to do regarding website assecibillity.

What do you think? Is this good? Should I change something?

Thanks :)

**Comment by bpvcode** [comment]
@brittanyjoiner15 , one more thing that I didn't find how to do it:
Can you assign this PR  to me and mark you as a reviewer? When I create the PR I found no way to do it, sorry...
If there is a way, can you explain me? :)

**Comment by brittanyjoiner15** [comment]
@bpvcode we just recently updated the PR template to leave out those steps because i realized that when you're not a maintainer in the repo you can't do that :) no worries, this is on my radar and i will probably take a look at it tomorrow!

In fact, if you'd like to join, I am doing a weekly live stream on fridays and will probably review this when i do it tomorrow at 12pm EST!

Here's the link if you want to join! https://youtu.be/ljgQIO9r8CI

**Comment by bpvcode** [comment]
Hello @brittanyjoiner15  , many thanks for sharing this information.

I will try to attend your live stream if I can quit earlier from job :) If not, will this be saved as a youtube video? 

Did you already review my PR? What do you think about my comments? Should I change something else?

I will open an issue that i really want to implement if you think that could make sense. It's basically implementing a tool that can give us reports on performance, accessibility, best practices, and SEO. I think this will be great because we can track our reports for each change that we do on the repo.

But to implement this I need to close this one first. So please give me your feedback when you can :)

Thanks :)

**Comment by brittanyjoiner15** [comment]
@bpvcode looking at this PR now! and yes live stream is being recorded! and ill try to remember to share the link in here but if forget, you can go to https://www.youtube.com/c/brittanyjoiner and go to past live streams and see it there!

**Review by brittanyjoiner15 — APPROVED** [review]
@bpvcode overall i like what you're suggesting here! And i think this is a great checklist to go off of. I love the priority scoring, and i think this a good list. 

Just want to clarify that "to do" means it something that needs to be done and will be a task to complete it. To check, simply means we need to go through the app and see if it exists. Right?  And you're saying we can have one issue for someone to go check through everything, and another issue(s) for people to implement the things that need to be done. Right? Just want to make sure I understand, but i think i am good with that approach if you want to create those issues. Let me know if you'd like to be assigned to them, or if you would like someone else to work on them.

Thanks for putting this together!

**Pull request merged**
