### PR TITLE
Create the light mode option

### LINKED ISSUE #44: Create light mode option
Right now the app is using Eui dark mode. Create a toggle to allow a user to enable light mode. 

You can learn more about how this works with Eui in the docs: https://elastic.github.io/eui/#/theming/theme-provider

Please check the various tabs and components while implementing as this may require some additional configuration on those.

### PR DESCRIPTION
**Pull request by NandanVyas**
# Add the light mode option
Resolves : https://github.com/brittanyjoiner15/eui-event-template/issues/44 
Fixed the visibility issues in the tab text.
Added light mode to the bottom bar.

### Screenshot of changes

Assignee - brittanyjoiner15
Assigned to - nandanvyas

### CODE REVIEW

**Comment by brittanyjoiner15** [comment]
More feedback that might help - 

You can try to use react-helmet and import the min styles from a free cdn: https://www.jsdelivr.com/

```
import { Helmet } from "react-helmet";

<Helmet>
  {theme === "light" ? (
    <link
      rel="stylesheet"
      href={
        "https://cdn.jsdelivr.net/npm/@elastic/eui@68.0.0/dist/eui_theme_light.min.css"
      }
    />
  ) : (
    <link
      rel="stylesheet"
      href={
        "https://cdn.jsdelivr.net/npm/@elastic/eui@68.0.0/dist/eui_theme_dark.min.css"
      }
    />
  )}
</Helmet>
```

**Review by brittanyjoiner15 — CHANGES_REQUESTED** [review]
Okay i think we're really close! There were a bunch of merge conflicts but i went ahead and resolved those so make sure to do `git pull` locally so that you get all of those updates.


Couple things that still need to be addressed before we can merge:

1. It seems there are two buttons but there should just be one. 
image

2. We need `react-helmet` in the `package.json` file so please make sure to include that!

3. Is there any way to prevent the toggle from jumping everytime we go to a new tab? See this example - it jumps to the side each time i go to a new tab. Not the biggest problem, but if we can fix that would be great. 

Kapture 2022-10-05 at 03 46 22


4. Lastly, can we make the toggle align with the buttons, so perhaps be a bit more centered? 
image

**Comment by NandanVyas** [comment]
Resolved Issues
  1. Two Buttons 
  2. Add `react-helmet` in the `package.json` file
  3. Prevent the toggle from jumping every time we go to a new tab.
  4. Align the toggle button with the other buttons

**Review by brittanyjoiner15 — APPROVED** [review]
Yes!! This is great! Thanks @NandanVyas ! And well done! I know this was a lot of work, so I really appreciate your efforts here.

**Pull request merged**
