### PR TITLE
Recordings tab added

### LINKED ISSUE #32: Create a tab for watching recordings of talks
Create a page that people can embed youtube videos on to show talks after the conference. 

Ideally it would be a page with two columns with embedded youtube videos.

### PR DESCRIPTION
**Pull request by Vaani-pathariya**
#### Describe your changes
I added another recordings tab that allows users to watch recordings in the website itself
#### Link to issue this resolves
fixes #32 
#### Screenshot of changes(if relevant)
image
the videos are random ones 

- [x] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_
- [x] This **description** should include ...
  - [x] A short summary of your changes
  - [x] A link to the issue that relates to these changes
  - [x] A screenshot of the changes if possible!
- [x] Add `brittanyjoiner15` as a reviewer
- [x] Add yourself as assignee

### CODE REVIEW

**Review by brittanyjoiner15 — CHANGES_REQUESTED** [review]
@Vaani-pathariya this looks really great!! The only thing i noticed is that when you shrink this to very small, it seems to cut off part of the video, so we maybe need to adjust the width on a very small screen?  See what I mean here:
cut-off-on-xs-screen

**Comment by Vaani-pathariya** [comment]
i did some more changes , now it should be fine .

**Comment by brittanyjoiner15** [comment]
@Vaani-pathariya looks great! merging now! thanks for your contribution!

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Does your team handle adding the desc to `how_it_works.md` or should we do that? I just synced with the repo and noticed the tab for this page was added but not the desc in `how_it_works.md`.

Wondering if I should add that for my own issue #34 or omit that. Thanks!

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell good point! We don't have a process in place for updating routes and docs, but we definitely should. I will fix it for this one, but if you can include the route in #34 that would be great!

**Pull request merged**
