### PR TITLE
Add navbar brand text routing and hover cursor

### LINKED ISSUE #65: [Improvement suggestion] As a user, I can click the navbar brand logo img and text to navigate back to the home page
Hi @brittanyjoiner15,

I'm new to open-source contributions and hoping to participate in my first hackathon. 

As the title suggest, I would like to propose a very simple improvement to UX to the navigation feature of your website based on what I am seeing on the production sample link. This feature would involve user feedback (i.e. a cursor change when hovering the navbar brand), in hopes of improving UX. 

Implementation Proposal: 
I am thinking of  adding `cursor: pointer` in the CSS and also making clicking the text navigate back to the homepage (in addition to the already implemented logo img). 

I havn't taken a look at the codebase yet but I would probably use react-dom or just using an `<a>` tag. 

Please let me know what you think about this and if it would be possible as contribution for hacktoberfest.

### PR DESCRIPTION
**Pull request by AloyBranCheung**
#### Describe your changes
* For the navbar, I added routing when clicking the brand text to navigate back home 
* For the navbar brand text and brand icon I added a `cursor: pointer` effect for better UI 

#### Link to issue this resolves
Closes #65

#### Screenshot of changes(if relevant)

* [ ] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_
* [ ] This **description** should include ...
  * [x] A short summary of your changes
  * [x] A link to the issue that relates to these changes
  * [ ] A screenshot of the changes if possible!
* [ ] Add `brittanyjoiner15` as a reviewer
* [x] Add yourself as assignee

### CODE REVIEW

**Review by brittanyjoiner15 — CHANGES_REQUESTED** [review]
So this one is a bit tricky because you totally have the right styles, but it's applying to the whole page title section, which goes all the way to the buttons and much past the text. (See example)

Kapture 2022-10-05 at 02 45 02


Do you think you could find a way to update those styles to only happen on the actual test? Or, maybe shrink the `pageTitle` element so that it doesn't span all the way across to the buttons?

**Comment by AloyBranCheung** [comment]
I took a look and I found that if I removed `flex-basis and flex-grow`
image

and added `justify-content: space-between`
image

it fixes the issue, I'm not sure how to tackle this with the EUI framework as I'm reading the EUI Page Header props and not finding a way to change their flex group https://elastic.github.io/eui/#/layout/page-header. 

Do you have any suggestions for me to approach this problem?

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung totally okay to fix it without using Eui! If you've got a fix that does it, then that will work. 

Can you commit those changes and push them so i can double check them and as long as it works alright I'm good to merge it!

**Comment by AloyBranCheung** [comment]
Hey @brittanyjoiner15 I'm actually having trouble tackling this issue. I've tried attaching css modules and using css selectors like `nth-child` to  `className` of e.g. `<EuiPageHeader className={styles.pageHeader} />` but to no avail, I am just editing the whole component instead of part of it. According to the docs I shouldn't be directly editing the eui classes as well, which makes sense. I'm not sure how to approach this other than creating the component from scratch i.e. without using EuiPageHeader or ?editing the framework itself. Could you please advise? Thanks.

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung i actually don't have any ideas either because I think this goes outside the scope of "Eui guidelines". I'm wondering if maybe it's actually not good practice to link the text and instead it should just be the logo. I'd prefer not to stray from the Eui framework with the header component. 

I've got an idea. Let's remove the stuff for linking the text, and instead, let's just change the text for `Event Details` tab to `Home`. Perhaps that would make it more clear how a user can "get back" to the "home" page, which I think is really the root of the issue. What do you think? Should be a pretty easy fix - you'll just need to check all the places we reference that tab name and update it.

**Comment by AloyBranCheung** [comment]
Hey @brittanyjoiner15, exciting news I think I solved it. I just added a max-width and it appears to be mobile-responsive too. Let me know what you think. If this solution is acceptable I'm going to cry with how complex I've been thinking 😂😂😭😭😭

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung yes i think you've got it!! well done!! thanks for working on this!

**Review by brittanyjoiner15 — APPROVED** [review]
Looks great!

**Comment by AloyBranCheung** [comment]
Thanks for your patience and guidance @brittanyjoiner15

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung so happy to help!

**Pull request merged**
