### PR TITLE
Issue#29 - Change title in header and hero image on Event Details panel

### PR DESCRIPTION
**Pull request by camillet16**
#### Describe your changes
- Changed header logo & text
- Changed event Image
- Changed event text to match the event image

#### Link to issue this resolves
[Issue #29](https://github.com/brittanyjoiner15/eui-event-template/issues/29)

#### Screenshot of changes(if relevant)
Screen Shot 2022-09-28 at 10 32 20 AM

- [x] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_
- [x] This **description** should include ...
  - [x] A short summary of your changes
  - [x] A link to the issue that relates to these changes
  - [x] A screenshot of the changes if possible!
- [x] Add `brittanyjoiner15` as a reviewer
- [x] Add yourself as assignee

### CODE REVIEW

**Comment by camillet16** [comment]
@brittanyjoiner15 I put in a pull request. I also want to raise a suggestion it might be good to limit the image size to align with the navbar width.  

Some advantages:
- This gives users the option to provide x2 image sizing which looks great on retina & 4k screens.
- The page would look better aligned.

☮️

**Comment by brittanyjoiner15** [comment]
@camillet16 hahah I LOVE this. You totally understood the assignment here 😂 It's perfect. I agree with your recommendations on matching image size to nav bar. Feel free to include that in this PR- did you already include that in this PR? Because im testing this branch locally and it does seem to do that, so thank you for including that!

One thing I did notice when i shrink the screen
image

This might be okay, but do you think we should change it so it wraps more nicely and doesn't cut off the word?  Admittedly it only happens on a very specific size - something larger than small but smaller than medium screens. Here's a loom demonstrating it: https://www.loom.com/share/4acef61d41194fcd8a293504cd01e8bf

If you don't think it's an issue, I'm good with leaving it as is, but if you can think of a quick way to fix it in case someone does it hit that very small screen. That might be good. 


Also i LOVE the creative angle you took with this! This is awesome! Let me know what you think about the above, and if you want to make any changes let me know, or if you're good to go, im happy to merge it (also i can wait until Oct 1st if you'd prefer for the merge to count towards Hacktoberfest). Thanks for working on this!

**Comment by camillet16** [comment]
@brittanyjoiner15 !!! I wanted to sort it out so badly but didn't have time to check if that was already in another issue. Definitely would love to sort it out, will update when it's ready. Let's do Oct 1 for the merge! 😄 It's my first hacktober so it would be nice if I could get them to plant a tree for me. 🌳

**Comment by brittanyjoiner15** [comment]
@camillet16 awesome!! welcome to hacktoberfest!! so glad to have you participating this year!! and yes we will definitely wait til Oct 1st!

**Comment by camillet16** [comment]
@brittanyjoiner15 everything's sorted. I, unfortunately, am not well-versed in typescript so I went onto App.css to fix both of them. 😅 Hope that's okay if not I can undo the last 3 commits just to fix the image and text change.

P.S. I did try sorting it out through the props but I'm not sure what might be the problem on _EuiPageHeader>pageTitleProps_  The sizing wasn't working or maybe I was misunderstanding it.

**Review by brittanyjoiner15 — APPROVED** [review]
@camillet16 these changes are perfect! I don't mind it wasn't in tailwind, doing it with CSS is totally fine with me! These changes look great, thank you so much! I'll go ahead and approve this and wait until the first to merge! Thanks so much for doing this!

**Comment by brittanyjoiner15** [comment]
@camillet16 merging this now! thanks for your contribution!

**Pull request merged**
