### PR TITLE
Reviewed contribution file, fixed grammar, and made some sub-title changes.

### LINKED ISSUE #18: Review contributing guidelines
Review [Contributing Guidelines](https://github.com/brittanyjoiner15/eui-event/blob/main/contributing.md) and fork a repo. Make suggestions to the docs about troubleshooting any issues you come across, or clarify any language that doesn't make sense. (Feel free to comment on here and ask for clarification on something, then take what you learn and update the markdown file).

### PR DESCRIPTION
**Pull request by diegoherrer4**
Reviewed and made changes to contribution file.

#### Screenshot of changes(if relevant)

Reviewer: `brittanyjoiner15`
Assignee: `diegoherrer4`

### CODE REVIEW

**Comment by diegoherrer4** [comment]
Please let me know if there are any further changes I can make, or if any changes I made were unnecessary or innefficient.

**Comment by brittanyjoiner15** [comment]
Thanks! I'll take a look probably tomorrow. Would you like me to wait til oct 1st to merge it?

**Comment by diegoherrer4** [comment]
Thank you, you can merge it whenever you wish :)

**Comment by brittanyjoiner15** [comment]
@diegoherrer4 this is great! Thank you for looking - and good catch with all those typos haha i love that i said `brain` instead of `branch` 😂 thanks for fixing all of that, this looks good to me, so I'll go ahead and merge!

**Pull request merged**
