### PR TITLE
Issue#35 add social link to footer

### PR DESCRIPTION
**Pull request by laxmanbalaraman**
#### Describe your changes
Added social links to footer and when clicked opens in a new tab

#### Link to issue this resolves
solve issue #35 

#### Screenshot of changes(if relevant)
Screenshot 2022-10-01 235239

* [x] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_
* [x] This **description** should include ...
  * [x] A short summary of your changes
  * [x] A link to the issue that relates to these changes
  * [x] A screenshot of the changes if possible!
* [ ] Add `brittanyjoiner15` as a reviewer
* [ ] Add yourself as assignee

### CODE REVIEW

**Comment by laxmanbalaraman** [comment]
Hey @brittanyjoiner15! My previous PR got closed. I clicked something in my cloned repo and messed up. So here is my new PR 
: (.
As requested the social icons now open in a new tab.

**Comment by brittanyjoiner15** [comment]
@laxmanbalaraman looks good! Thanks!

**Comment by laxmanbalaraman** [comment]
@brittanyjoiner15 Thanks for the Merge!
As a beginner to git and GitHub, I definitely learned a lot.
Happy hacktober! 😄

**Comment by brittanyjoiner15** [comment]
@laxmanbalaraman that's awesome!! Glad to hear it!! Happy Hacktoberfest!

**Pull request merged**
