### PR TITLE
added contributor file with names

### PR DESCRIPTION
**Pull request by ArshErgon**
for the issue #39
a script could be possible but the number of calls are limited to normal users, not for premium. And we actually required the owners API token.
so I just created a small python program which fetch all the pull requests, filter out the username check it inside a hashmap, and if it doesn't it add that name and update the` contributors.md` file.

### CODE REVIEW

**Comment by brittanyjoiner15** [comment]
@ArshErgon makes sense! Thanks for researching this!

**Review by brittanyjoiner15 — APPROVED** [review]
Thanks for updating this!

**Comment by ArshErgon** [comment]
hey @brittanyjoiner15  I found something hope this will help to update the contribution.md https://allcontributors.org/

**Comment by brittanyjoiner15** [comment]
@ArshErgon oooh this is interesting! I'll add queue this up to take a look! thanks!

**Pull request merged**
