### PR TITLE
Navbar full width 

### LINKED ISSUE #121: Minor UI fixes
On both live/local website:

1. Logo changes on switching theme
 
image
image

2. Full width container for navbar will look better
image

On local server:

1. `<svg>` icons are not visible.

image
image

2. Button flicker on toggle

https://user-images.githubusercontent.com/35252877/198667609-e881a25b-0fe8-405a-abd4-7dada2f070e2.mp4

---

I will contribute after discussion and getting assigned.

### PR DESCRIPTION
**Pull request by adsingh14**
### Describe your changes
Navbar is now utilizing full width.

#### Link to issue this resolves

Fixes #121 
#### Screenshot of changes(if relevant)
image

- [x] The **title** should be something descriptive about what you're changes do. _(It will default to whatever you put as your commit message.)_

##### This **description** should include :
   - [x] A short summary of your changes
   
   - [x] A link to the issue that relates to these changes
   
   - [x] A screenshot of the changes if possible!

### CODE REVIEW

**Comment by brittanyjoiner15** [comment]
@adsingh14 that was a quick fix!! Can you revert the changes to the package-lock and the yarn lock? Don't think we need those changes in there. I assume that happened cause you ran `npm` instead of `yarn`, which is totally fine, but i think it could mess things up if we push all that into main.

**Review by brittanyjoiner15 — CHANGES_REQUESTED** [review]
Will approve and merge this after you revert the `package-lock.json` and `yarn.lock` changes. Thanks!

**Comment by adsingh14** [comment]
@brittanyjoiner15
> cause you ran npm instead of yarn

I installed npm but using yarn command-line. 

>Will approve and merge this after you revert the package-lock.json and yarn.lock changes. Thanks!

Alright!

**Comment by brittanyjoiner15** [comment]
@adsingh14 yeah, no problem! just let me know when those changes in those files are reverted and ill check in here again!

**Comment by adsingh14** [comment]
Done ! Have a look at those files.

**Review by brittanyjoiner15 — APPROVED** [review]
Looks great! Thanks!

**Comment by adsingh14** [comment]
> Authorization required to deploy.

How to resolve this ?

**Comment by brittanyjoiner15** [comment]
@adsingh14 ill go ahead and merge! Got distracted with another issue and forgot to merge this one. Will do it now!

**Pull request merged**
