### PR TITLE
Add FAQs tab

### LINKED ISSUE #34: Add an FAQ tab
Create a tab with some lorem ipsum text with FAQs about the conference/event.

### PR DESCRIPTION
**Pull request by brandonmcconnell**
## Describe your changes
This pull request…

* adds an FAQ page/tab to the template, utilizing Elastic UI's Accordion ([`EuiAccordion`](https://elastic.github.io/eui/#/layout/accordion))
  * added accompanying route
  * added description of tab to `how_it_works.md`
* adds globally accessible references to Elastic UI's colors, both as exported variables for JS use and custom properties for CSS use
* adds new responsive hooks for easier breakpoint-dependent style management
  * `xs`
    * `useIsXs`
    * `useAboveXs`
  * `s`
    * `useIsS`
    * `useBelowS`
    * `useAboveS`
  * `m`
    * `useIsM`
    * `useBelowM`
    * `useAboveM`
  * `l`
    * `useIsL`
    * `useBelowL`
    * `useAboveL`
  * `xl`
    * `useIsXl`
    * `useBelowXl`

## Link to issue this resolves
Resolves #34

## Screenshot of changes
| Desktop | Mobile |
|----|----|
|screencapture-localhost-3000-faq-2022-10-02-02!UNITO-UNDERSCORE!29!UNITO-UNDERSCORE!53 |screencapture-localhost-3000-faq-2022-10-02-02!UNITO-UNDERSCORE!29!UNITO-UNDERSCORE!43 |

## Screen recording
https://user-images.githubusercontent.com/5913254/193441289-1aba0ae8-de13-4415-bb58-68eaff8da6a2.mp4

### CODE REVIEW

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Looks like I can't assign this directly to you. This might be because I used a fork rather than the generated template, however, when I was formerly using the generated approach, I was unable to sync with the parent repo, which is why I then switched to a fork.

**Review by brittanyjoiner15 — APPROVED** [review]
@brandonmcconnell this looks awesome!! Such a good job!! I love it!! And thanks for the attention to detail and updating the routes and the how it works!! I can't think of any requested changes here - this is exactly what i was looking for!

And don't worry about assigning me - i need to update the PR template because I actually don't think most folks can assign themselves or request me as a review, but i get the notification so it works! 

Thanks again for this contribution! Very well done!

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Glad to hear it!

With this one wrapped up, are there any other front-end-oriented tickets coming down the pike I can take on (other than #70, which I'll try to take on next weekend)?

Some ideas:
* Responsive styling
* Maybe adding Tailwind support (unless this work against the EUI methodology)
* Any additional widgets/components/tab needed
  * Toast notifications
  * Add to calendar button
  * Blog setup, maybe with headless CMS integration (this one would be big, so if you'd want it, it would be nice to see if there would be some sensible milestone at which to split the request into 2 issues/PRs)
* Any additional hooks or EUI abstractions
* Any other fancy JS/CSS magic you can think of! (animations, transitions, special blending mode effects, whatever)

I'd love to devote the rest of my Hacktoberfest quota to this project if there's work available to fill it 🙂

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell awesome, love the enthusiasm and would love to have your help.

Re: 
- responsive styling -  the site should be fairly responsively styled, but if you see any specific areas that could be improved, feel free to spin up issues
- tailwind support - this would probably be used in Lieue of Eui since that's a design library with its own styles
- what kind of toast notification are you picturing? as in what would trigger that? Feel free to spin up an issue showing what you mean and where you think it would be used
- we do already have an [`add to calendar` button](https://github.com/brittanyjoiner15/eui-event-template/blob/main/src/utilities/addCalButtons.jsx), but if you have ideas on how to improve it, feel free to create an issue! 
- I don't necessarily think we need a blog, and that would be quite a big project, maybe feel free to create an issue for this and I wouldn't highly prioritize it but it could be something to work on 
- i think there are a lot of sections that could be refactored to be written more cleanly, but i haven't had time to really look into it. if you see any that you think could be improved, create an issue!

**Pull request merged**
