### PR TITLE
Create the light mode option

### LINKED ISSUE #44: Create light mode option
Right now the app is using Eui dark mode. Create a toggle to allow a user to enable light mode. 

You can learn more about how this works with Eui in the docs: https://elastic.github.io/eui/#/theming/theme-provider

Please check the various tabs and components while implementing as this may require some additional configuration on those.

### PR DESCRIPTION
**Pull request by NandanVyas**
# Add the light mode option
Resolves : https://github.com/brittanyjoiner15/eui-event-template/issues/44 

### Screenshot of changes

Assignee - brittanyjoiner15
Assigned to - nandanvyas

### CODE REVIEW

**Review by brittanyjoiner15 — CHANGES_REQUESTED** [review]
Great job on this so far, but a couple changes please: 
- [ ] Can you pull from main and fix the merge conflicts? Also might want to rebase with Main because we've had a lot of changes in the app since this version, so it might be worth getting all up to date and then implementing the changes. (Let me know if you've never done this before and need help.)
- [ ] It looks like the footer still shows in dark mode even when light mode is selected
- [ ] The table also still shows in dark mode even when light mode is selected
- [ ] The tab text is not very visible in light mode
- [ ] 

image

image

image

**Comment by brittanyjoiner15** [comment]
@NandanVyas hey there, i see you closed this. Are you still planning to work on it?

**Comment by NandanVyas** [comment]
Actually I didn’t close it , it happened itself when I pulled the new changes in the main to my fork and I have already started working on the issues one by one. Just completed the footer part will be working on the table and tabs next.

**Comment by brittanyjoiner15** [comment]
@NandanVyas sounds good, feel free to re-open whenever it's ready for review, thanks!

**Pull request closed without merging**
